# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='internal_name',
        ),
    ]
