# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190204_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.IntegerField(blank=True, choices=[(1, 'Available'), (2, 'Out Of Stock'), (3, 'Not Available')], default=2),
        ),
    ]
