# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190204_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, b'Submitted'), (2, b'In-progress'), (3, b'Complete'), (4, b'Cancelled')], default=1, max_length=25),
        ),
    ]
